##
## Copyright (C) 2014-2026 V-Nova International Limited
##
##     * All rights reserved.
##     * This software is licensed under the BSD-3-Clause-Clear License.
##     * No patent licenses are granted under this license. For enquiries about patent
##       licenses, please contact legal@v-nova.com.
##     * The software is a stand-alone project and is NOT A CONTRIBUTION to any other
##       project.
##     * If the software is incorporated into another project, THE TERMS OF THE
##       BSD-3-CLAUSE-CLEAR LICENSE AND THE ADDITIONAL LICENSING INFORMATION CONTAINED
##       IN THIS FILE MUST BE MAINTAINED, AND THE SOFTWARE DOES NOT AND MUST NOT ADOPT
##       THE LICENSE OF THE INCORPORATING PROJECT. However, the software may be
##       incorporated into a project under a compatible license provided the
##       requirements of the BSD-3-Clause-Clear license are respected, and V-Nova
##       International Limited remains licensor of the software ONLY UNDER the
##       BSD-3-Clause-Clear license (not the compatible license).
##
## ANY ONWARD DISTRIBUTION, WHETHER STAND-ALONE OR AS PART OF ANY OTHER PROJECT,
## REMAINS SUBJECT TO THE EXCLUSION OF PATENT LICENSES PROVISION OF THE
## BSD-3-CLAUSE-CLEAR LICENSE.
##

name: CI

on:
  pull_request:
  push:
    tags:
      - "*"

env:
  BUILD_TYPE: Release

permissions: {}

jobs:
  set-vars:
    name: Variables
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      VERSION: ${{ steps.output.outputs.VERSION }}
    steps:
      - name: Set version
        id: output
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Run Lint Check
        run: |
          sudo apt-get install -y clang-format-14 clang-tidy-14 libgtest-dev
          git ls-files -z '**/*.h' '**/*.c' '**/*.hpp' '**/*.cpp' ':!:third_party/**' | xargs -0 clang-format-14 --style=file --dry-run -Werror
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/install -DVN_BUILD_UNIT_TESTS=ON
          run-clang-tidy-14 -p build -j $(nproc)

  build-linux:
    name: Build - Linux
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    needs: ["set-vars"]
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: CMake - Build
        run: |
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release
          cmake --install build --config Release

      - name: Execute
        run: |
          export LD_LIBRARY_PATH=$(pwd)/build/install/lib:$LD_LIBRARY_PATH
          ./build/install/bin/lcevc_stream_analyzer --version

      - name: Archive
        env:
          ARCHIVE: "lcevc_stream_analyzer-${{needs.set-vars.outputs.VERSION}}-linux-x86_64"
        run: |
          tar -cvf $ARCHIVE.tar.gz build/install/bin/lcevc_stream_analyzer third_party/LICENSES LICENSE COPYING

      - name: Upload
        env:
          ARCHIVE: "lcevc_stream_analyzer-${{needs.set-vars.outputs.VERSION}}-linux-x86_64"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{env.ARCHIVE}}
          path: ${{env.ARCHIVE}}.tar.gz

  build-macos:
    name: Build - macOS
    runs-on: macos-15
    permissions:
      contents: read
    needs: ["set-vars"]
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: CMake - Build
        run: |
          echo $ARCHIVE
          brew install cmake
          brew install git
          brew install pkgconf
          brew install ffmpeg
          brew install aom
          brew install googletest

          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release
          cmake --install build --config Release

      - name: Archive
        env:
          ARCHIVE: "lcevc_stream_analyzer-${{needs.set-vars.outputs.VERSION}}-macos-aarch64"
        run: |
          tar -cvf $ARCHIVE.tar.gz build/install/bin/lcevc_stream_analyzer third_party/LICENSES LICENSE COPYING

      - name: Upload
        env:
          ARCHIVE: "lcevc_stream_analyzer-${{needs.set-vars.outputs.VERSION}}-macos-aarch64"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{env.ARCHIVE}}
          path: ${{env.ARCHIVE}}.tar.gz

  build-windows-msvc:
    name: Build - Windows MSVC
    runs-on: windows-2025
    permissions:
      contents: read
    needs: ["set-vars"]
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Build
        shell: cmd # zizmor: ignore[misfeature] can't load vcvars without cmd
        run: |
          md build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release
          cmake --install build --config Release

      - name: Execute
        run: |
          build\install\bin\lcevc_stream_analyzer.exe --version

      - name: Archive
        shell: powershell
        env:
          ARCHIVE: "lcevc_stream_analyzer-${{needs.set-vars.outputs.VERSION}}-windows-x86_64"
        run: |
          mkdir archive
          cp LICENSE archive\
          cp COPYING archive\

          mkdir archive\third_party\
          cp -r third_party\LICENSES archive\third_party\

          mkdir archive\bin
          cp build\install\bin\lcevc_stream_analyzer.exe archive\bin\

          Compress-Archive -Path archive\* -DestinationPath "$env:ARCHIVE.zip"

      - name: Upload
        env:
          ARCHIVE: "lcevc_stream_analyzer-${{needs.set-vars.outputs.VERSION}}-windows-x86_64"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{env.ARCHIVE}}
          path: ${{env.ARCHIVE}}.zip

  build-windows-mingw:
    name: Build - Windows MinGW
    runs-on: windows-2025
    permissions:
      contents: read
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Build - Prepare MinGW
        uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda # v2
        with:
          msystem: UCRT64
          install: mingw-w64-ucrt-x86_64-gcc cmake ninja

      - name: Build - CMake
        run: |
          mkdir build
          cmake -G Ninja -S . -B build -DCMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release
          cmake --install build --config Release

      - name: Execute
        run: |
          ./build/install/bin/lcevc_stream_analyzer --version

  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      [
        "build-linux",
        "build-macos",
        "build-windows-msvc",
        "build-windows-mingw",
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Gather
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: release/

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ls release
          ls release/*
          gh release create ${VERSION} release/*/*
